### ISSUE TITLE
Current status/Todo list

### ISSUE THREAD

**Issue by ethindp** [ethindp/kernel#2]
Here is what we have so far and what needs to be done. Contributions appreciated! Feel free to jump right in and start development of anything on this list -- there's lots to do!

Dependencies are marked in parentheses alongside each todo item, if any. The majority of these tasks depend on a number of issues that need to be closed first, so not all of these can be done in parallel.

* X86-specific
    * [x] #28
    * [x] #27
    * [x] #29
    * [ ] #3 (#33)
    * [ ] #4 (#33)
    * [x] #6
    * [x] #30
    * [x] #31
    * [x] #32
    * [ ] #5 (#33)
    * [ ] #7 (#33, #6, #4)
    * [ ] #8 (#7 or #12, #33)
    * [ ] #9 (#33)
    * [ ] #10 (#33)
    * [ ] #11 (#7, #14, #18, #20, #22, #23, #24, #33)
    * [ ] #12 (#4, #6, #33)
    * [ ] #13 (#3, #4, #5, #6, #7, #8, #9, #11, #13, #14, #15, #17, #18, #19, #20, #22, #23, #24, #33)
    * [ ] #14 (driver-dependent but definitely #33)
    * [ ] #15 (#14, #3, #4, #6, #7, #8, #33)
    * [ ] #16 (all other issues other than #25 and #26)
    * [ ] #17 (#33)
    * [ ] #18 (#3, #33)
    * [ ] #19 (#33)
    * [ ] #20 (#14, #33)
    * [ ] #21 (#14, #33)
    * [ ] #22 (#13, #14, #33)
    * [ ] #23 (#13, #14, #20, #21, #7, #3, #4, #6, #8, #9, #10, #11, #12, #17, #15, #33)
    * [ ] #24 (all other issues)
    * [x] #33
* Other/lowest priority work (for now)
    * [ ] #25
* Code related
    * [ ] #26
